### PR TITLE
Add section to docs detailing opening an ST project from the command line.

### PR DESCRIPTION
**Pull request by AllanLRH**
ST automatically stripped trailing spaces, which creates a lot of "noise" in the diff... but feel welcome to just pick out the part with the section about the command line :)

### CODE REVIEW

**Comment by aviaryan** [comment]
Wow. I had no idea I had left so many trailing spaces.

**Comment by aviaryan** [comment]
Regarding your addition, I can see that it has been added 2 times. Please fix this. 
Also, add it as a point in the FAQ section (last section) and link it in the "Accessing your Notes" section via something like "Learn about opening your notebook via the command line [here]".

**Comment by AllanLRH** [comment]
I've made some changes — please have another look.

**Comment by aviaryan** [comment]
Hi @AllanLRH. Thanks for the update.
I have found one more issue, unfortunately. It seems to happen that some trailing spaces were on purpose, like the one in TOC. WIthout that, we have this -

screen shot 2018-02-08 at 7 44 57 pm

**Comment by AllanLRH** [comment]
Sorry, I didn't think to check that. Added back some spaces.

**Comment by aviaryan** [comment]
Thanks for the update @AllanLRH but now you have removed the stuff that this PR is for. Take it easy, man! 😄

**Comment by AllanLRH** [comment]
Haha, wierd! I tried to be smart with git, but was apparently outsmarted.... I tried again, but in a less "clever way".

**Comment by aviaryan** [comment]
Thanks!

**Pull request merged**
